import os
import webbrowser
from datetime import datetime

from docx import Document
from pptx import Presentation
from pptx.util import Inches
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


# ============================================================
# JARVIS FEATURE MODULE
# This file ADDS features.
# It does NOT replace your existing main.py.
# ============================================================


BASE_DIR = os.path.dirname(os.path.abspath(__file__))

GENERATED_DIR = os.path.join(BASE_DIR, "generated")

PDF_DIR = os.path.join(GENERATED_DIR, "pdf")
WORD_DIR = os.path.join(GENERATED_DIR, "word")
PPT_DIR = os.path.join(GENERATED_DIR, "ppt")


os.makedirs(PDF_DIR, exist_ok=True)
os.makedirs(WORD_DIR, exist_ok=True)
os.makedirs(PPT_DIR, exist_ok=True)


# ============================================================
# HELPER
# ============================================================

def safe_filename(text):
    """Convert a topic into a safe Windows filename."""

    invalid = '<>:"/\\|?*'

    for char in invalid:
        text = text.replace(char, "_")

    return text.strip()


# ============================================================
# PDF CREATOR
# ============================================================

def create_pdf(topic, content=None):

    topic = topic.strip()

    if not content:
        content = f"""
This document was created by JARVIS.

Topic:
{topic}

Introduction

This document provides an overview of {topic}.

Key Concepts

The topic can be studied by understanding its basic concepts,
important terminology, practical applications, advantages,
limitations, and security considerations.

Conclusion

Understanding {topic} provides a useful foundation for further
study and practical work.
"""

    filename = safe_filename(topic) + ".pdf"

    filepath = os.path.join(PDF_DIR, filename)

    document = SimpleDocTemplate(
        filepath,
        pagesize=A4
    )

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(topic, styles["Title"])
    )

    story.append(
        Spacer(1, 20)
    )

    for paragraph in content.split("\n"):

        paragraph = paragraph.strip()

        if paragraph:

            story.append(
                Paragraph(
                    paragraph,
                    styles["BodyText"]
                )
            )

            story.append(
                Spacer(1, 8)
            )

    document.build(story)

    return filepath


# ============================================================
# WORD DOCUMENT CREATOR
# ============================================================

def create_word(topic, content=None):

    topic = topic.strip()

    if not content:
        content = f"""
Introduction

This document was created by JARVIS.

The topic of this document is {topic}.

Key Concepts

The subject can be understood by studying its important concepts,
terminology, applications, advantages, limitations and practical
examples.

Conclusion

Further study and practical experimentation can provide a deeper
understanding of {topic}.
"""

    filename = safe_filename(topic) + ".docx"

    filepath = os.path.join(WORD_DIR, filename)

    document = Document()

    document.add_heading(topic, 0)

    document.add_paragraph(
        "Generated by JARVIS"
    )

    for paragraph in content.split("\n"):

        paragraph = paragraph.strip()

        if paragraph:

            document.add_paragraph(paragraph)

    document.save(filepath)

    return filepath


# ============================================================
# POWERPOINT CREATOR
# ============================================================

def create_powerpoint(topic, content=None):

    topic = topic.strip()

    if not content:
        content = f"""
Introduction

{topic} is an important subject that can be studied through
its concepts, applications and practical examples.

Key Concepts

Understanding the fundamental concepts of {topic} is the first
step toward learning the subject.

Applications

{topic} can have practical applications depending on the
specific field and problem being studied.

Advantages

Understanding {topic} can improve technical knowledge and
problem-solving ability.

Challenges

There can be practical, technical and security challenges
associated with {topic}.

Best Practices

Following appropriate methods and learning from practical
examples can improve understanding.

Conclusion

{topic} can be explored further through practical exercises,
research and experimentation.
"""

    filename = safe_filename(topic) + ".pptx"

    filepath = os.path.join(PPT_DIR, filename)

    presentation = Presentation()

    # Title slide
    slide = presentation.slides.add_slide(
        presentation.slide_layouts[0]
    )

    slide.shapes.title.text = topic

    slide.placeholders[1].text = (
        "Generated by JARVIS"
    )

    # Content slides
    paragraphs = [
        p.strip()
        for p in content.split("\n")
        if p.strip()
    ]

    current_title = None
    current_text = []

    for paragraph in paragraphs:

        # Treat short lines as headings
        if len(paragraph) < 45:

            if current_title:

                slide = presentation.slides.add_slide(
                    presentation.slide_layouts[1]
                )

                slide.shapes.title.text = current_title

                slide.placeholders[1].text = (
                    "\n".join(current_text)
                )

            current_title = paragraph
            current_text = []

        else:

            current_text.append(paragraph)

    # Add final slide
    if current_title:

        slide = presentation.slides.add_slide(
            presentation.slide_layouts[1]
        )

        slide.shapes.title.text = current_title

        slide.placeholders[1].text = (
            "\n".join(current_text)
        )

    presentation.save(filepath)

    return filepath


# ============================================================
# CREATE ALL THREE
# ============================================================

def create_all_documents(topic, content=None):

    pdf = create_pdf(topic, content)

    word = create_word(topic, content)

    ppt = create_powerpoint(topic, content)

    return {
        "pdf": pdf,
        "word": word,
        "ppt": ppt
    }


# ============================================================
# OPEN GENERATED FILE
# ============================================================

def open_file(filepath):

    if os.path.exists(filepath):

        os.startfile(filepath)

        return True

    return False


# ============================================================
# DIRECT WEBSITE FUNCTIONS
# ============================================================

def open_youtube():

    webbrowser.open(
        "https://www.youtube.com/"
    )


def search_youtube(query):

    url = (
        "https://www.youtube.com/results?search_query="
        + query.replace(" ", "+")
    )

    webbrowser.open(url)


def open_spotify():

    webbrowser.open(
        "https://open.spotify.com/"
    )


def search_spotify(query):

    url = (
        "https://open.spotify.com/search/"
        + query.replace(" ", "%20")
    )

    webbrowser.open(url)


def open_instagram():

    webbrowser.open(
        "https://www.instagram.com/"
    )


def open_whatsapp():

    webbrowser.open(
        "https://web.whatsapp.com/"
    )


def open_gmail():

    webbrowser.open(
        "https://mail.google.com/"
    )


def open_linkedin():

    webbrowser.open(
        "https://www.linkedin.com/"
    )


def open_calendar():

    webbrowser.open(
        "https://calendar.google.com/"
    )


def open_github():

    webbrowser.open(
        "https://github.com/"
    )


def open_google():

    webbrowser.open(
        "https://www.google.com/"
    )


# ============================================================
# PYTHON ERROR EXPLAINER
# ============================================================

def explain_python_error(error):

    error_text = str(error)

    if "SyntaxError" in error_text:

        return """
JARVIS Python Tutor

Error type:
SyntaxError

Meaning:
Python found invalid Python syntax.

Common causes:
- Missing colon :
- Missing bracket
- Missing quotation mark
- Incorrect indentation
- Invalid Python statement

Check the line mentioned by Python and the line immediately
before it.
"""

    if "IndentationError" in error_text:

        return """
JARVIS Python Tutor

Error type:
IndentationError

Meaning:
Python found incorrect indentation.

Check:
- Spaces
- Tabs
- Code blocks
- if/for/while/function indentation
"""

    if "NameError" in error_text:

        return """
JARVIS Python Tutor

Error type:
NameError

Meaning:
Python cannot find the variable or function name.

Check:
- Spelling
- Whether the variable was created
- Whether the correct name was used
"""

    if "ModuleNotFoundError" in error_text:

        return """
JARVIS Python Tutor

Error type:
ModuleNotFoundError

Meaning:
Python cannot find the requested module.

Possible fix:

pip install <module-name>

Also check that your virtual environment is activated.
"""

    if "TypeError" in error_text:

        return """
JARVIS Python Tutor

Error type:
TypeError

Meaning:
An operation or function received an incorrect type of value.

Example:

"10" + 5

A string and integer cannot normally be added directly.
"""

    if "ValueError" in error_text:

        return """
JARVIS Python Tutor

Error type:
ValueError

Meaning:
The correct type of value was expected, but the value itself
was not acceptable.
"""

    if "FileNotFoundError" in error_text:

        return """
JARVIS Python Tutor

Error type:
FileNotFoundError

Meaning:
Python could not find the requested file.

Check:
- File name
- File extension
- Folder path
- Current working directory
"""

    return f"""
JARVIS Python Tutor

I detected this error:

{error_text}

Send me the complete traceback and I can explain:

1. What the error means
2. Why it happened
3. Which line caused it
4. How to fix it
5. Corrected code
"""


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    print("=" * 50)
    print("JARVIS FEATURE MODULE TEST")
    print("=" * 50)

    topic = "Python Exception Handling"

    print("\nCreating documents...")

    files = create_all_documents(topic)

    print("\nPDF:")
    print(files["pdf"])

    print("\nWord:")
    print(files["word"])

    print("\nPowerPoint:")
    print(files["ppt"])

    print("\nAll documents created successfully!")

    print("\nGenerated folders:")
    print(GENERATED_DIR)